// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiHLZhKasg9jEypSYPUW2fse5aJo45ci0',
    appId: '1:655860970964:web:ef055aa50289bcfeaa5241',
    messagingSenderId: '655860970964',
    projectId: 'judgy-bramp-net',
    authDomain: 'judgy-bramp-net.firebaseapp.com',
    storageBucket: 'judgy-bramp-net.firebasestorage.app',
    measurementId: 'G-JV4VEKQWXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhNETFl0PwZAIJe4yc7-atNHtqz6SVDQ',
    appId: '1:655860970964:android:f887611c82505c6eaa5241',
    messagingSenderId: '655860970964',
    projectId: 'judgy-bramp-net',
    storageBucket: 'judgy-bramp-net.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYVewj5g0LnIfM5XhidmL1sv8BNnwiio',
    appId: '1:655860970964:ios:a029e77788af5b71aa5241',
    messagingSenderId: '655860970964',
    projectId: 'judgy-bramp-net',
    storageBucket: 'judgy-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.judgy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdYVewj5g0LnIfM5XhidmL1sv8BNnwiio',
    appId: '1:655860970964:ios:a029e77788af5b71aa5241',
    messagingSenderId: '655860970964',
    projectId: 'judgy-bramp-net',
    storageBucket: 'judgy-bramp-net.firebasestorage.app',
    iosBundleId: 'net.bramp.judgy',
  );
}
